name: Add all issues and prs to project board

on:
  issues:
    types:
      - opened
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  add-to-project:
    name: Add to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/users/Urganot/projects/2
          #labeled: bug, needs-triage
          #label-operator: OR
